### ISSUE TITLE
How do I add an audio that automatically plays when opening the website?

### ISSUE THREAD

**Issue by lokky000** [codeschool-projects/HTMLPortfolioProject#404]

**Comment by Fazalkadivar21** [comment]
how about adding the autoplay attribute?

**Comment by Touseefwaqas** [comment]
You can use autoplay attribute in the audio tag.

**Comment by prashantrai-30** [comment]
I'm interested in contributing to this issue. 
I have a potential solution in mind and would like to discuss it before proceeding.
Please let me know if there's any additional information needed or if you have any suggestions for how I should proceed.
